# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}
      - run: mkdir solanaj
        name: Create SolanaJ directory
      - run: cd solanaj
        name: Navigate to SolanaJ directory
      - uses: actions/checkout@v2
        with:
          repository: skynetcapital/solanaj
          ref: v1.5
      - name: Build SolanaJ with Maven
        run: mvn clean install
      - run: cd ../
        name: Navigate to root maven directory
      - uses: actions/checkout@v2
      - name: Package solanaj-spring-boot-sdk with Maven
        run: mvn -B package --file pom.xml
